version: '3.8'

services:
  placement-dashboard:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PPO_SESSION_ID=${PPO_SESSION_ID}
      - INTERNSHIP_SESSION_ID=${INTERNSHIP_SESSION_ID}
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
